---
title           : "The Effect of Variance of an Applied Perturbation on Learning Rate, Generalisation and Washout in a Feedforward Experiment"
shorttitle      : "Preregistration"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Sandrine Hinrichs
    affiliation : 1
  - name        : David Kaplan
    affiliation : "2"
  - name        : Matthew Crossley
    affiliation : "2"
  - name        : Christopher Hewitson
    affiliation : "2"

affiliation:
  - id          : 1
    institution : Georg-August-University Goettingen
  - id          : 2
    institution : Macquarie University Sydney

output: prereg::cos_prereg
---


# Study Information

## Title
<!-- Provide the working title of your study. It may be the same title that you submit for publication of your final manuscript, but it is not a requirement. The title should be a specific and informative description of a project. Vague titles such as 'Fruit fly preregistration plan' are not appropriate.

Example: Effect of sugar on brownie tastiness. -->

`r rmarkdown::metadata$title`


## Description
<!-- Please give a brief description of your study, including some background, the purpose of the of the study, or broad research questions. The description should be no longer than the length of an abstract. It can give some context for the proposed study, but great detail is not needed here for your preregistration.

Example: Though there is strong evidence to suggest that sugar affects taste preferences, the effect has never been demonstrated in brownies. Therefore, we will measure taste preference for four different levels of sugar concentration in a standard brownie recipe to determine if the effect exists in this pastry. -->

Does feedforward adaptation to a visuomotor perturbation follow a Bayesian framework? In their seminal paper Körding and Wolpert (2004) have shown that humans can learn a probability distribution of visuomotor perturbations as a prior and that this learning process is further affected by the amount of uncertainty of the visual input. However, as most of the following research, they have only shown that this applies to the mean of a probability distribution and, so far, little is known about the question whether also additional information of the distribution of an imposed perturbation such as its variance is encoded and learned. An investigation specifically of the effect of variance of an imposed perturbation on learning would, however, be crucial for a better understanding of the Bayesian implementation of the brain in sensorimotor adaptation. The purpose of the present study is to investigate the effect of variance on learning, washout and generalisation to other targets in a feedforward experimental design.


## Hypotheses
<!-- List specific, concise, and testable hypotheses. Please state if the hypotheses are directional or non-directional. If directional, state the direction. A predicted effect is also appropriate here. If a specific interaction or moderation is important to your research, you can list that as a separate hypothesis.

Example: If taste affects preference, then mean preference indices will be higher with higher concentrations of sugar. -->

**Learning:** The effect of variance of a perturbation probability distribution on learning rate is still poorly studied. Fernandes et al. (2012) report lower variance leading to a higher and faster learning rate. However, a strong directional prediction would require a more solid basis of previous literature, especially considering paradigm differences. We, therefore, choose the more statistically conservative non-directional hypothesis, expecting the amount of variance leading to a difference in learning rate.  

**Washout:** As is the case with learning, evidence of variance influencing washout is poor. Results of Canaveral et al. (2017) weakly suggest that training under a more variable perturbation schedule increases the uncertainty of the adapted forward model and lead to weaker retention. However, their chosen variances are first much smaller and second drawn from a multinomial as opposed to a normal distribution. Those changes in paradigm make predictions for this study even more unreliable. We, thus, also choose a non-directional hypothesis here, stating that a difference in variance influences washout rate.

**Generalisation:** Fernandes et al. (2012) reported no significant differences in generalisation width after manipulating the perturbation variance. Assuming that variance has an effect on learning rate we would, however, at least expect a different amplitude between different variance conditions. In line with the previous two hypotheses, our conservative non-directional hypothesis states that varying the amount of variance would result in a difference in generalisation.



# Design Plan
<!-- In this section, you will be asked to describe the overall design of your study. Remember that this research plan is designed to register a single study, so if you have multiple experimental designs, please complete a separate preregistration. -->


## Study type

**Experiment**. A researcher randomly assigns treatments to study subjects, this includes field or lab experiments. This is also known as an intervention experiment and includes randomized controlled trials.



## Blinding
<!-- Blinding describes who is aware of the experimental manipulations within a study. Select all that apply. Is there any additional blinding in this study? -->

For studies that involve human subjects, they will not know the treatment group to which they have been assigned.


## Study design
<!-- Describe your study design. Examples include two-group, factorial, randomized block, and repeated measures. Is it a between (unpaired), within-subject (paired), or mixed design? Describe any counterbalancing required. Typical study designs for observation studies include cohort, cross sectional, and case-control studies.

This question has a variety of possible answers. The key is for a researcher to be as detailed as is necessary given the specifics of their design. Be careful to determine if every parameter has been specified in the description of the study design. There may be some overlap between this question and the following questions. That is OK, as long as sufficient detail is given in one of the areas to provide all of the requested information. For example, if the study design describes a complete factorial, 2 X 3 design and the treatments and levels are specified previously, you do not have to repeat that information.

Example: We have a between subjects design with 1 factor (sugar by mass) with 4 levels. -->

The present study involves a between-subjects design with a factor rotation variance, i.e. the variance of the respectively imposed perturbation, with the three group levels 0°, 4° and 12° and the factor rotation direction with the two levels clockwise (CW) vs. counter clockwise (CCW).



## Randomisation
<!-- If you are doing a randomized study, how will you randomize, and at what level? Typical randomization techniques include: simple, block, stratified, and adaptive covariate randomization. If randomization is required for the study, the method should be specified here, not simply the source of random numbers.

Example: We will use block randomization, where each participant will be randomly assigned to one of the four equally sized, predetermined blocks. The random number list used to create these four blocks will be created using the web applications available at http://random.org. -->

Participants will randomly be assigned to a rotation direction and a rotation variance group respectively. In order to ensure the same number of participants per group we will create a vector of 24 ones (CCW) and zeros (CW) respectively for rotation direction and another one with 16 zeros (0°), ones (4°) and twos (12°) respectively for the rotation variance. Subsequently, we pseudorandomised the resulting vectors using the `sample` function in R. The vector of participant indices (representing the order of their assignment to the experiment) will then be merged with those pseudorandomised rotation direction and rotation variance vectors.


# Sampling Plan
<!-- In this section we’ll ask you to describe how you plan to collect samples, as well as the number of samples you plan to collect and your rationale for this decision. Please keep in mind that the data described in this section should be the actual data used for analysis, so if you are using a subset of a larger dataset, please describe the subset that will actually be used in your study. -->


## Existing data
<!-- Preregistration is designed to make clear the distinction between confirmatory tests, specified prior to seeing the data, and exploratory analyses conducted after observing the data. Therefore, creating a research plan in which existing data will be used presents unique challenges. Please select the description that best describes your situation. Please do not hesitate to contact us if you have questions about how to answer this question (prereg@cos.io). -->

**Registration prior to creation of data**. As of the date of submission of this research plan for preregistration, the data have not yet been collected, created, or realized. 



## Explanation of existing data
<!-- If you indicate that you will be using some data that already exist in this study, please describe the steps you have taken to assure that you are unaware of any patterns or summary statistics in the data. This may include an explanation of how access to the data has been limited, who has observed the data, or how you have avoided observing any analysis of the specific data you will use in your study.

An appropriate instance of using existing data would be collecting a sample size much larger than is required for the study, using a small portion of it to conduct exploratory analysis, and then registering one particular analysis that showed promising results. After registration, conduct the specified analysis on that part of the dataset that had not been investigated by the researcher up to that point.

Example: An appropriate instance of using existing data would be collecting a sample size much larger than is required for the study, using a small portion of it to conduct exploratory analysis, and then registering one particular analysis that showed promising results. After registration, conduct the specified analysis on that part of the dataset that had not been investigated by the researcher up to that point. -->

We don't have any existing data so far.


## Data collection procedures
<!-- Please describe the process by which you will collect your data. If you are using human subjects, this should include the population from which you obtain subjects, recruitment efforts, payment for participation, how subjects will be selected for eligibility from the initial pool (e.g. inclusion and exclusion rules), and your study timeline. For studies that don’t include human subjects, include information about how you will collect samples, duration of data gathering efforts, source or location of samples, or batch numbers you will use.

The answer to this question requires a specific set of instructions so that another person could repeat the data collection procedures and recreate the study population. Alternatively, if the study population would be unable to be reproduced because it relies on a specific set of circumstances unlikely to be recreated (e.g., a community of people from a specific time and location), the criteria and methods for creating the group and the rationale for this unique set of subjects should be clear.

Example: Participants will be recruited through advertisements at local pastry shops. Participants will be paid $10 for agreeing to participate (raised to $30 if our sample size is not reached within 15 days of beginning recruitment). Participants must be at least 18 years old and be able to eat the ingredients of the pastries. -->

We will use the Macquarie University first year psychology SONA Participant Pool for recruitment. Participants will be rewarded with 4 credits after completion. Only right-hand dominant participants with normal or corrected to normal vision will be eligible for this study. 


## Sample size
<!-- Describe the sample size of your study. How many units will be analysed in the study? This could be the number of people, birds, classrooms, plots, interactions, or countries included. If the units are not individuals, then describe the size requirements for each unit. If you are using a clustered or multilevel design, how many units are you collecting at each level of the analysis? For some studies, this will simply be the number of samples or the number of clusters. For others, this could be an expected range, minimum, or maximum number.

Example: Our target sample size is 280 participants. We will attempt to recruit up to 320, assuming that not all will complete the total task. -->

Our minimum sample size consists of 27 participants, 9 per group. However, we will attempt to recruit 48 participants, 16 per group (see section sample size rationale below). 


## Sample size rationale
<!-- This could include a power analysis or an arbitrary constraint such as time, money, or personnel. This gives you an opportunity to specifically state how the sample size will be determined. A wide range of possible answers is acceptable; remember that transparency is more important than principled justifications. If you state any reason for a sample size upfront, it is better than stating no reason and leaving the reader to "fill in the blanks." Acceptable rationales include: a power analysis, an arbitrary number of subjects, or a number based on time or monetary constraints.

Example: We used the software program G*Power to conduct a power analysis. Our goal was to obtain .95 power to detect a medium effect size of .25 at the standard .05 alpha error probability. -->

After running a power analysis in the free software program G*Power to reach a power of 0.95 with a significance level of alpha = 0.05 using a one-sided paired t-test we determined a minimum sample size of 9 participants per group. Based on the smallest reported effect size of Fernandes et al. (2012) the effect size was set to a decrease of 5.7° in the second group. However, as we are changing their within-subjects design to a between-subjects design this result should be treated with caution and, hence, we plan to recruit additional 7 subjects per group resulting in a total amount of 16 subjects per group. Participant numbers are consistent with field-standard conventions for studies of visuomotor adaptation and generalisation (Krakauer et al., 2000; Krakauer et al., 1999; Brayanov et al., 2012; Fernandez et al., 2012).


## Stopping rule
<!-- If your data collection procedures do not give you full control over your exact sample size, specify how you will decide when to terminate your data collection. 

You may specify a stopping rule based on p-values only in the specific case of sequential analyses with pre-specified checkpoints, alphas levels, and stopping rules. Unacceptable rationales include stopping based on p-values if checkpoints and stopping rules are not specified. If you have control over your sample size, then including a stopping rule is not necessary, though it must be clear in this question or a previous question how an exact sample size is attained.

Example: We will post participant sign-up slots by week on the preceding Friday night, with 20 spots posted per week. We will post 20 new slots each week if, on that Friday night, we are below 320 participants. -->

As long as we haven't reached the total amount of 48 participants, we will continue posting weekly sign-up slots. All slots will be deleted as soon as 48 subjects participated in the study.



# Variables
<!-- In this section you can describe all variables (both manipulated and measured variables) that will later be used in your confirmatory analysis plan. In your analysis plan, you will have the opportunity to describe how each variable will be used. If you have variables which you are measuring for exploratory analyses, you are not required to list them, though you are permitted to do so. -->


## Manipulated variables
<!-- Describe all variables you plan to manipulate and the levels or treatment arms of each variable. This is not applicable to any observational study. For any experimental manipulation, you should give a precise definition of each manipulated variable. This must include a precise description of the levels at which each variable will be set, or a specific definition for each categorical treatment. For example, “loud or quiet,” should instead give either a precise decibel level or a means of recreating each level. 'Presence/absence' or 'positive/negative' is an acceptable description if the variable is precisely described.

Example: We manipulated the percentage of sugar by mass added to brownies. The four levels of this categorical variable are: 15%, 20%, 25%, or 40% cane sugar by mass. -->

We manipulated two variables, rotation direction and rotation variance. Both variables are categorical with the factor levels clockwise (CW), counter clockwise (CCW) and 0°, 4° and 12° sd respectively. 


## Measured variables
<!-- Describe each variable that you will measure. This will include outcome measures, as well as any predictors or covariates that you will measure. You do not need to include any variables that you plan on collecting if they are not going to be included in the confirmatory analyses of this study.

Observational studies and meta-analyses will include only measured variables. As with the previous questions, the answers here must be precise. For example, 'intelligence,' 'accuracy,' 'aggression,' and 'color' are too vague. Acceptable alternatives could be 'IQ as measured by Wechsler Adult Intelligence Scale' 'percent correct,' 'number of threat displays,' and 'percent reflectance at 400 nm.'

Example: The single outcome variable will be the perceived tastiness of the single brownie each participant will eat. We will measure this by asking participants ‘How much did you enjoy eating the brownie’ (on a scale of 1-7, 1 being 'not at all', 7 being 'a great deal') and 'How good did the brownie taste' (on a scale of 1-7, 1 being 'very bad', 7 being 'very good'). -->

**Outcome measure:** Our outcome measure will be the baseline corrected endpoint error (EE), i.e. the distance between the actual target location and the participants hand position when the threshold of 9cm is reached in degrees. 


## Indices
<!-- If any measurements are  going to be combined into an index (or even a mean), what measures will you use and how will they be combined? Include either a formula or a precise description of your method. If your are using a more complicated statistical method to combine measures (e.g. a factor analysis), you can note that here but describe the exact method in the analysis plan section.

If you are using multiple pieces of data to construct a single variable, how will this occur? Both the data that are included and the formula or weights for each measure must be specified. Standard summary statistics, such as "means" do not require a formula, though more complicated indices require either the exact formula or, if it is an established index in the field, the index must be unambiguously defined. For example, "biodiversity index" is too broad, whereas "Shannon’s biodiversity index" is appropriate.

Example: We will take the mean of the two questions above to create a single measure of 'brownie enjoyment.'  -->

We will baseline correct EEs in adaptation and re-adaptation using the baseline trials with feedback and EEs in generalisation and washout using the baseline trials without feedback. For this purpose, the mean per target in the respective baseline block is computed over trials and subtracted from the respective EE in the adaptation, re-adaptation, generalisation and washout block.  


# Analysis Plan
<!-- You may describe one or more confirmatory analysis in this preregistration. Please remember that all analyses specified below must be reported in the final article, and any additional analyses must be noted as exploratory or hypothesis generating.

A confirmatory analysis plan must state up front which variables are predictors (independent) and which are the outcomes (dependent), otherwise it is an exploratory analysis. You are allowed to describe any exploratory work here, but a clear confirmatory analysis is required. -->


## Statistical models
<!-- What statistical model will you use to test each hypothesis? Please include the type of model (e.g. ANOVA, multiple regression, SEM, etc) and the specification of the model (this includes each variable that will be included as predictors, outcomes, or covariates). Please specify any interactions, subgroup analyses, pairwise or complex contrasts, or follow-up tests from omnibus tests. If you plan on using any positive controls, negative controls, or manipulation checks you may mention that here. Remember that any test not included here must be noted as an exploratory test in your final article.

This is perhaps the most important and most complicated question within the preregistration. As with all of the other questions, the key is to provide a specific recipe for analysing the collected data. Ask yourself: is enough detail provided to run the same analysis again with the information provided by the user? Be aware for instances where the statistical models appear specific, but actually leave openings for the precise test. See the following examples:

- If someone specifies a 2x3 ANOVA with both factors within subjects, there is still flexibility with the various types of ANOVAs that could be run. Either a repeated measures ANOVA (RMANOVA) or a multivariate ANOVA (MANOVA) could be used for that design, which are two different tests. 
- If you are going to perform a sequential analysis and check after 50, 100, and 150 samples, you must also specify the p-values you’ll test against at those three points.

Example:  We will use a one-way between subjects ANOVA to analyze our results. The manipulated, categorical independent variable is 'sugar' whereas the dependent variable is our taste index. -->

...


## Transformations
<!-- If you plan on transforming, centering, recoding the data, or will require a coding scheme for categorical variables, please describe that process. If any categorical predictors are included in a regression, indicate how those variables will be coded (e.g. dummy coding, summation coding, etc.) and what the reference category will be.

Example: The "Effect of sugar on brownie tastiness" does not require any additional transformations. However, if it were using a regression analysis and each level of sweet had been categorically described (e.g. not sweet, somewhat sweet, sweet, and very sweet), 'sweet' could be dummy coded with 'not sweet' as the reference category. -->

... 


## Inference criteria
<!-- What criteria will you use to make inferences? Please describe the information youÍll use (e.g. p-values, bayes factors, specific model fit indices), as well as cut-off criterion, where appropriate. Will you be using one or two tailed tests for each of your analyses? If you are comparing multiple conditions or testing multiple hypotheses, will you account for this?

p-values, confidence intervals, and effect sizes are standard means for making an inference, and any level is acceptable, though some criteria must be specified in this or previous fields. Bayesian analyses should specify a Bayes factor or a credible interval. If you are selecting models, then how will you determine the relative quality of each? In regards to multiple comparisons, this is a question with few "wrong" answers. In other words, transparency is more important than any specific method of controlling the false discovery rate or false error rate. One may state an intention to report all tests conducted or one may conduct a specific correction procedure; either strategy is acceptable.

Example: We will use the standard p<.05 criteria for determining if the ANOVA and the post hoc test suggest that the results are significantly different from those expected if the null hypothesis were correct. The post-hoc Tukey-Kramer test adjusts for multiple comparisons. -->

...


## Data exclusion
<!-- How will you determine what data or samples, if any, to exclude from your analyses? How will outliers be handled? Will you use any awareness check? Any rule for excluding a particular set of data is acceptable. One may describe rules for excluding a participant or for identifying outlier data.

Example: No checks will be performed to determine eligibility for inclusion besides verification that each subject answered each of the three tastiness indices. Outliers will be included in the analysis. -->

A participant’s data will be excluded in the case of a participant not completing the whole experiment or if a participant’s data will get corrupted in any possible manner. In those cases, this data will not be analysed and the respective number of new subjects will be recruited.
In order to reduce explicit strategies, we will add a time constraint such that participants have a total time of 600ms to reach the target. Trials in which participants don't reach the 9cm threshold will be excluded. 


## Missing data
<!-- How will you deal with incomplete or missing data? Any relevant explanation is acceptable. As a final reminder, remember that the final analysis must follow the specified plan, and deviations must be either strongly justified or included as a separate, exploratory analysis.

Example: If a subject does not complete any of the three indices of tastiness, that subject will not be included in the analysis. -->

Missing trials due to a participant exceeding the time constraint will be treated in the following way:
- If a subject’s amount of missing values in at least one of the baseline, post-baseline, adaptation, re-adaptation or washout phase exceeds a 10% threshold respectively or in the case of less than 5 successful reaches per target in the generalisation phase the respective subject will be excluded from the analysis.
- Otherwise, we will run a simulation to ensure that the threshold of 10% is appropriate. If yes, analyses will be conducted considering those trials as missing values. 
- If, however, the result of the simulation suggests that the threshold of 10% has been set too low and that a more restrictive threshold would be more appropriate for data analysis participants will be excluded according to the more appropriate threshold. 


## Exploratory analyses (optional)
<!-- If you plan to explore your data set to look for unexpected differences or relationships, you may describe those tests here. An exploratory test is any test where a prediction is not made up front, or there are multiple possible tests that you are going to use. A statistically significant finding in an exploratory test is a great way to form a new confirmatory hypothesis, which could be registered at a later time.

Example: We expect that certain demographic traits may be related to taste preferences. Therefore, we will look for relationships between demographic variables (age, gender, income, and marital status) and the primary outcome measures of taste preferences. -->

**Initial prior:**
We will analyse the pre-familiarisation data to investigate the prior based only on proprioception, i.e. the movements occluded participants conduct to reach to a specific target before any feedback and, thus, any prior is being imposed. Are there some systematic patterns? What is the participants initial prior when exposed to this new reaching task without the respective visual input?

**Endpoint error (EE) vs. initial movement vector (IMV):**
We are further interested in comparing EE to IMV. As the present stud design is meant to be a pure feedforward design, we expect no systematic difference between EE and IMV. The reason we chose EE as our dependent measure is due to the high amount of noise we found in the IMV of our pilot study. EE in contrast was much less noisy. We, however, decided to additionally include IMV to explore the relationship of those two measures in this feedforward design.

**Implicit vs. explicit learning:**
Previous literature suggests gaze as a way to distinguish between implicit and explicit strategies in sensorimotor adaptation (Anouk et al., 2018). Even though this relationship needs further research for better confirmation we are interested in this possible way of disentangling those two strategy types and, therefore, plan to analyse eye tracking data while participants perform the sensorimotor adaptation task. We assume that the implementation of explicit strategies would let the learning curve immediately increase at its maximum after only few trials as opposed to a gradual shift that would be expected in the implicit case. 

We will further implement the questionnaire of Benson et al. (2011) at the end of the study to relate the eye tracking data to the conscient use of explicit strategies. This would allow us to investigate specific pattern differences in gaze and movement data between participants who learned only implicitly and those who additionally implemented explicit strategies.


# Other

## Other (Optional)
<!-- If there is any additional information that you feel needs to be included in your preregistration, please enter it here. Literature cited, disclosures of any related work such as replications or work that uses the same data, or other context that will be helpful for future readers would be appropriate here. -->

Enter your response here.


# References
## 
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
\noindent
